config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  resources :users, only: [:new, :create]
  resources :rooms, only: [:index, :new, :create, :show]

  resources :rooms do
    resources :messages, only: [:create]
  end
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :content, type: String

  validates :content, presence: true, length: { maximum: 140 }

  belongs_to :room, inverse_of: :messages
  belongs_to :user, inverse_of: nil

  default_scope -> { order(created_at: :asc) }
end

app/models/room.rb
class Room
  include Mongoid::Document
  field :name, type: String

  validates :name, presence: true, length: { maximum: 50 }
  index({ name: 1 }, { unique: true })

  has_many :messages
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :token, type: String

  has_many :messages

  validates :name, presence: true, length: { maximum: 50 }
  validates :token, presence: true, length: { minimum: 28 }

  index({token: 1}, {unique: true})

  attr_readonly :token

  before_validation do |user|
    user[:token] = SecureRandom.base64(21)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include UsersHelper

  private
      # Confirms a logged-in user
      def logged_in_user
        unless logged_in?
          redirect_to root_url
        end
      end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.build(content: params[:message][:content], user: current_user)
    @message.save
    redirect_to room_path(@room)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(name: params[:room][:name])
    if @room.save
      redirect_to room_path(@room)
    else
      redirect_to rooms_path
    end
  end

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = @room.messages.build
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to rooms_path
    end
  end

  def create
    @user = User.new(name: params[:user][:name])
    if @user.save
      session[:user_token] = @user.token
      redirect_to rooms_path
    else
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if (user_token = session[:user_token])
      @current_user ||= User.find_by(token: user_token)
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<li><strong><%= message.user.name %>:</strong> <%= message.content %></li>

app/views/rooms/_message_form.html.erb
<%= form_for(@message, url: room_messages_path(@room)) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit "Enviar" %>
<% end %>

app/views/rooms/_room.html.erb
<li><%= link_to room.name, room %></li>

app/views/rooms/index.html.erb
<%= link_to "Crear sala", new_room_path %>
<ul>
  <%= render @rooms %>
</ul>

app/views/rooms/new.html.erb
<%= form_for(@room) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Crear" %>
<% end %>

app/views/rooms/show.html.erb
<%= link_to "Volver a listado de salas", rooms_path %>
<h3>Mensajes:</h3>
<div id="message-feed">
  <%= render @messages %>
</div>

<%= render 'message_form' %>

app/views/users/new.html.erb
<%= form_for(:user, url: users_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Entrar", class: "btn btn-primary" %>
<% end %>